services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: vorm_dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - ALLOWED_ORIGINS=http://localhost:5173
    ports:
      - 3001:3001
      - 5173:5173
    container_name: vorm_dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18.2
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - pg_data:/data
    container_name: vorm_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pg_data:
    name: vorm_pg_data
