/*
  This file has been mostly generated by AI (~97% by line count)
*/

import type { PlainNetworkGraphData } from '../../../../common/types/network'

export const parseGraphData = (value: string): PlainNetworkGraphData | null => {
  try {
    const parsed = JSON.parse(value)
    if (parsed && Array.isArray(parsed.nodes) && Array.isArray(parsed.links)) return parsed
  } catch {
    // not valid JSON yet, leave as-is
  }
  return null
}

export const nextUniqueId = (prefix: string, taken: Set<string>) => {
  let i = taken.size + 1
  while (taken.has(`${prefix}-${i}`)) i++
  return `${prefix}-${i}`
}

export const hasDuplicateIds = (data: PlainNetworkGraphData): boolean => {
  const nodeIds = new Set<string>()
  for (const node of data.nodes) {
    if (node?.id == null) continue
    if (nodeIds.has(node.id)) return true
    nodeIds.add(node.id)
  }

  const linkIds = new Set<string>()
  for (const link of data.links) {
    if (link?.id == null) continue
    if (linkIds.has(link.id) || nodeIds.has(link.id)) return true
    linkIds.add(link.id)
  }

  return false
}
