/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IlluRouteImport } from './routes/illu'
import { Route as IllustrationsRouteRouteImport } from './routes/illustrations/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IllustrationsIndexRouteImport } from './routes/illustrations/index'
import { Route as IllustrationsIllustrationIdRouteRouteImport } from './routes/illustrations/$illustrationId/route'
import { Route as IllustrationsIllustrationIdIndexRouteImport } from './routes/illustrations/$illustrationId/index'
import { Route as IllustrationsIllustrationIdEditRouteImport } from './routes/illustrations/$illustrationId/edit'

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IlluRoute = IlluRouteImport.update({
  id: '/illu',
  path: '/illu',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationsRouteRoute = IllustrationsRouteRouteImport.update({
  id: '/illustrations',
  path: '/illustrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationsIndexRoute = IllustrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IllustrationsRouteRoute,
} as any)
const IllustrationsIllustrationIdRouteRoute =
  IllustrationsIllustrationIdRouteRouteImport.update({
    id: '/$illustrationId',
    path: '/$illustrationId',
    getParentRoute: () => IllustrationsRouteRoute,
  } as any)
const IllustrationsIllustrationIdIndexRoute =
  IllustrationsIllustrationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => IllustrationsIllustrationIdRouteRoute,
  } as any)
const IllustrationsIllustrationIdEditRoute =
  IllustrationsIllustrationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => IllustrationsIllustrationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/illustrations': typeof IllustrationsRouteRouteWithChildren
  '/illu': typeof IlluRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/testing': typeof TestingRoute
  '/illustrations/$illustrationId': typeof IllustrationsIllustrationIdRouteRouteWithChildren
  '/illustrations/': typeof IllustrationsIndexRoute
  '/illustrations/$illustrationId/edit': typeof IllustrationsIllustrationIdEditRoute
  '/illustrations/$illustrationId/': typeof IllustrationsIllustrationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/illu': typeof IlluRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/testing': typeof TestingRoute
  '/illustrations': typeof IllustrationsIndexRoute
  '/illustrations/$illustrationId/edit': typeof IllustrationsIllustrationIdEditRoute
  '/illustrations/$illustrationId': typeof IllustrationsIllustrationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/illustrations': typeof IllustrationsRouteRouteWithChildren
  '/illu': typeof IlluRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/testing': typeof TestingRoute
  '/illustrations/$illustrationId': typeof IllustrationsIllustrationIdRouteRouteWithChildren
  '/illustrations/': typeof IllustrationsIndexRoute
  '/illustrations/$illustrationId/edit': typeof IllustrationsIllustrationIdEditRoute
  '/illustrations/$illustrationId/': typeof IllustrationsIllustrationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/illustrations'
    | '/illu'
    | '/login'
    | '/register'
    | '/testing'
    | '/illustrations/$illustrationId'
    | '/illustrations/'
    | '/illustrations/$illustrationId/edit'
    | '/illustrations/$illustrationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/illu'
    | '/login'
    | '/register'
    | '/testing'
    | '/illustrations'
    | '/illustrations/$illustrationId/edit'
    | '/illustrations/$illustrationId'
  id:
    | '__root__'
    | '/'
    | '/illustrations'
    | '/illu'
    | '/login'
    | '/register'
    | '/testing'
    | '/illustrations/$illustrationId'
    | '/illustrations/'
    | '/illustrations/$illustrationId/edit'
    | '/illustrations/$illustrationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IllustrationsRouteRoute: typeof IllustrationsRouteRouteWithChildren
  IlluRoute: typeof IlluRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TestingRoute: typeof TestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illu': {
      id: '/illu'
      path: '/illu'
      fullPath: '/illu'
      preLoaderRoute: typeof IlluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustrations': {
      id: '/illustrations'
      path: '/illustrations'
      fullPath: '/illustrations'
      preLoaderRoute: typeof IllustrationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustrations/': {
      id: '/illustrations/'
      path: '/'
      fullPath: '/illustrations/'
      preLoaderRoute: typeof IllustrationsIndexRouteImport
      parentRoute: typeof IllustrationsRouteRoute
    }
    '/illustrations/$illustrationId': {
      id: '/illustrations/$illustrationId'
      path: '/$illustrationId'
      fullPath: '/illustrations/$illustrationId'
      preLoaderRoute: typeof IllustrationsIllustrationIdRouteRouteImport
      parentRoute: typeof IllustrationsRouteRoute
    }
    '/illustrations/$illustrationId/': {
      id: '/illustrations/$illustrationId/'
      path: '/'
      fullPath: '/illustrations/$illustrationId/'
      preLoaderRoute: typeof IllustrationsIllustrationIdIndexRouteImport
      parentRoute: typeof IllustrationsIllustrationIdRouteRoute
    }
    '/illustrations/$illustrationId/edit': {
      id: '/illustrations/$illustrationId/edit'
      path: '/edit'
      fullPath: '/illustrations/$illustrationId/edit'
      preLoaderRoute: typeof IllustrationsIllustrationIdEditRouteImport
      parentRoute: typeof IllustrationsIllustrationIdRouteRoute
    }
  }
}

interface IllustrationsIllustrationIdRouteRouteChildren {
  IllustrationsIllustrationIdEditRoute: typeof IllustrationsIllustrationIdEditRoute
  IllustrationsIllustrationIdIndexRoute: typeof IllustrationsIllustrationIdIndexRoute
}

const IllustrationsIllustrationIdRouteRouteChildren: IllustrationsIllustrationIdRouteRouteChildren =
  {
    IllustrationsIllustrationIdEditRoute: IllustrationsIllustrationIdEditRoute,
    IllustrationsIllustrationIdIndexRoute:
      IllustrationsIllustrationIdIndexRoute,
  }

const IllustrationsIllustrationIdRouteRouteWithChildren =
  IllustrationsIllustrationIdRouteRoute._addFileChildren(
    IllustrationsIllustrationIdRouteRouteChildren,
  )

interface IllustrationsRouteRouteChildren {
  IllustrationsIllustrationIdRouteRoute: typeof IllustrationsIllustrationIdRouteRouteWithChildren
  IllustrationsIndexRoute: typeof IllustrationsIndexRoute
}

const IllustrationsRouteRouteChildren: IllustrationsRouteRouteChildren = {
  IllustrationsIllustrationIdRouteRoute:
    IllustrationsIllustrationIdRouteRouteWithChildren,
  IllustrationsIndexRoute: IllustrationsIndexRoute,
}

const IllustrationsRouteRouteWithChildren =
  IllustrationsRouteRoute._addFileChildren(IllustrationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IllustrationsRouteRoute: IllustrationsRouteRouteWithChildren,
  IlluRoute: IlluRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TestingRoute: TestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
